# Generated by Django 5.1.6 on 2025-03-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
