# Generated by Django 5.1.6 on 2025-03-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_owner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscriber",
            new_name="TaskSubscriber",
        ),
    ]
