# Generated by Django 5.1.6 on 2025-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_rename_subscriber_tasksubscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
