# Generated by Django 5.1.6 on 2025-02-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies: list = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="project",
        ),
        migrations.RemoveField(
            model_name="subscriber",
            name="task",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectMember",
        ),
        migrations.DeleteModel(
            name="Subscriber",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
