name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Isort  
        uses: isort/isort-action@v1
        with:
          configuration: "--check-only --diff --profile=black"

      - name: Run black
        uses: psf/black@stable

      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'

      - name: Install Poetry
        run: |
            curl -sSL https://install.python-poetry.org | python3 -
  
  
      - name: Install dependencies
  
        run: |
          poetry install --no-root
  
  
          - name: Set DJANGO_SETTINGS_MODULE

           run: echo "DJANGO_SETTINGS_MODULE=core.settings" >> $GITHUB_ENV
    
    
      - name: Set PYTHONPATH    
        run: echo "PYTHONPATH=$(pwd)/application" >> $GITHUB_ENV
    
    
      - name: Run tests with pytest
    
        run: |
          poetry run pytest --cov=application
  
  
      - name: Run tests with pytest
  
        run: |
  
          poetry run pytest --cov=application

