name: CI

on:
  push:
    branches:
      - main
      - dev
      - features/setup
  pull_request:
    branches:
      - main
      - dev
      - features/setup

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.0.1

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run pre-commit
        run: |
          poetry run pre-commit run --all-files