name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Isort  
        uses: isort/isort-action@v1
        with:
          configuration: "--check-only --diff --profile=black"

      - name: Run black
        uses: psf/black@stable

      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file      
        run: |
            echo "${{ secrets.env }}" >> .env

      - name: Docker up
        run: |
          docker compose up -d
          
    
      - name: Run tests with pytest
        run: |
          docker compose exec web poetry run pytest application/ --cov
  
      - name: Install diff-cover
        run: |
          pip install diff-cover    

      - name: Generate coverage report
        run: |
          docker compose exec web poetry run coverage xml
  
      - name: Run diff-cover
        run: |
          diff-cover coverage.xml --compare-branch=main/${{ github.base_ref }}   

          
  
  

